//
//  WorkshopController.swift
//  EncircleWinterSummit
//
//  Created by Kaden Hendrickson on 11/6/19.
//  Copyright © 2019 DevMountain. All rights reserved.
//

import UIKit

class WorkshopController  {
    
    //MARK - singleton
    static let shared = WorkshopController()
    //MARK - Properties
    var workshopsForTrack: [[Workshop]] = []
    
    var openingSessionTime = setWorkshopTime(hour: 12, minute: 15)
    var youthSharedSessionTime = setWorkshopTime(hour: 13, minute: 30)
    var sessionOneTime = setWorkshopTime(hour: 14, minute: 30)
    var sessionTwoTime = setWorkshopTime(hour: 15, minute: 30)
    var sessionThreeTime = setWorkshopTime(hour: 16, minute: 30)
    var dinnerSessionTime = setWorkshopTime(hour: 17, minute: 30)
    var closingSessionTime = setWorkshopTime(hour: 18, minute: 00)

    //MARK - Functions

    private static func setWorkshopTime(hour: Int, minute: Int) -> Date {
        var dateComponents = DateComponents()
        dateComponents.year = 2019
        dateComponents.month = 12
        dateComponents.day = 7
        dateComponents.timeZone = TimeZone(abbreviation: "MST")
        dateComponents.hour = hour
        dateComponents.minute = minute

        let calender = Calendar.current
        guard let date = calender.date(from: dateComponents) else {return Date()}
        return date
    }
    
//    func setWorkshopsForTrack(){
//  	      switch UserController.shared.currentUser?.trackPreference {
//        case .youth:
//            workshopsForTrack = youthWorkshops
//        case .youngAdult:
//            workshopsForTrack = youngAdultWokshops
//        case .adult:
//            print("hi")
//            return adultWorkhops
//        case .parent:
//            return parentWorkshops
//        case .educator:
//            return educatorWorkshops
//        default:
//            return youthWorkshops
//        }
//        print("😩😩😩😩😩workshops for track got changed to \(UserController.shared.currentUser?.trackPreference)😩😩😩😩😩😩😩😩😩😩")
//    }
    


    
    //Intro and Outro Workshops
    var youthIntroAndOutroWorkshops: [Workshop] {
        let openeingSession = Workshop(name: "Opening Session", title: "Opening Session", time: openingSessionTime , description: "(Overflow available in AlphaBravo)", room: "Main Area", map: "opening Map")
        let firstWorkshop = Workshop(name: "Workshop 1", title: "FirstWorkshop", time: youthSharedSessionTime, description: "This is just a placeholder for the first youth and young adult workshop", room: "alphabravo", map: "Adobe-1")
        let dinner = Workshop(name: "Dinner", title: "Dinner", time: dinnerSessionTime, description: "The moment you've all been waiting for!", room: "Main Area", map: "opening Map")
        let closingSession = Workshop(name: "Closing Session", title: "Closing Session", time: closingSessionTime, description: "(Overflow available in AlphaBravo)", room: "Main Area", map: "opening Map")
        return [openeingSession,firstWorkshop, dinner, closingSession]
    }
    
    var adultIntroAndOutroWorkshops: [Workshop] {
       let openeingSession = Workshop(name: "Opening Session", title: "Opening Session", time: openingSessionTime, description: "(Overflow available in AlphaBravo)", room: "Main Area", map: "opening Map")
          let dinner = Workshop(name: "Dinner", title: "Dinner", time: dinnerSessionTime, description: "The moment you've all been waiting for!", room: "Main Area", map: "opening Map")
          let closingSession = Workshop(name: "Closing Session", title: "Closing Session", time: closingSessionTime, description: "(Overflow available in AlphaBravo)", room: "Main Area", map: "opening Map")
          return [openeingSession, dinner, closingSession]
    }
    
    
    //YOUTH WORKSHOPS
    var youthWorkshops: [[Workshop]] {
        var youthWorkshop1: [Workshop] {
            let workshop1 = Workshop(name: "Workshop 2", title: "BEYOND", time: sessionOneTime, description: "A night of music in which all members of the community are welcome to come sing, play/bring instruments, laugh, and jam together.", room: "Music Room", map: "Adobe-3")
            let workshop2 = Workshop(name: "Workshop 2", title: "Tools to Thrive: Featuring Trevor Project", time: sessionOneTime, description: "Suicide Prevention and Crisis Response, Freaturing Trevor Project", room: "Tesla", map: "Adobe-3")
            let workshop3 = Workshop(name: "Workshop 2", title: "Elevate", time: sessionOneTime, description: "A speaking series in which Encircle invites successful, thriving, inspirational LGBTQ+ individuals with diverse backgrounds and life journeys from the community to come and share their story.", room: "Pele/Ruth", map: "Adobe-2")
            let workshop4 = Workshop(name: "Workshop 2", title: "WayOUT Panel", time: sessionOneTime, description: "WayOUT was started by a group of friends in San Francisco to help change what it means to grow up as a sexual minority in America. Come chat with three of wayOUT's members about their own personal experiences from coming out to building their professional careers and everything in between.", room: "Pollock", map: "Adobe-1")
            let workshop5 = Workshop(name: "Workshop 2", title: "Trans Experiences: Understanding, navigating and normalizing", time: sessionOneTime, description: "This Workshop invites participants to hear stories and share their personal experiences with intersectional gender, race and class. Peppermint will share her journey and discuss how it influences who she is today.", room: "Spielberg/Lucas", map: "Adobe-1")
            let workshop6 = Workshop(name: "Workshop 2", title: "Love Louder Art Series", time: sessionOneTime, description: "Add color to your life through creative and artistic expression. This workshop hosted by masters of their craft provides new skills and coping strategies. No artistic experience necessary!", room: "Alphabravo", map: "Adobe-1")
            let workshop7 = Workshop(name: "Workshop 2", title: "Blue Sky", time: sessionOneTime, description: "Clear away cloudy days by putting pencil to paper. This workshop provides a safe space to find your voice through writing. ", room: "Miyamoto", map: "Adobe-4")
            let workshop8 = Workshop(name: "Workshop 2", title: "Friendship Circles", time: sessionOneTime, description: "FIND SUPPORT, VALIDATION, AND LEARN FROM EACH OTHER’S EXPERIENCES", room: "Hoff/Cailiau/Torvalds/Geschke", map: "Adobe-4")
            let workshop9 = Workshop(name: "Workshop 2", title: "Rainbow Mutual", time: sessionOneTime, description: "Come make Rainbow Pins with your friends!", room: "Gould/Bell", map: "Adobe-3")
            let workshop10 = Workshop(name: "Workshop 2", title: "Gender Q&A Panel", time: sessionOneTime, description: "A panel of transgender, gender non-conforming, and a partner of someone who is will be opening up about their identities, their experiences, and their lives. Come listen to them tell their stories, and ask questions. Learn about gender identity, and what that can look like in a variety of ways.", room: "Newton", map: "Adobe-3")
            let workshop11 = Workshop(name: "Workshop 1", title: "Tools to Thrive", time: sessionOneTime, description: "Join Dolls of Hope in a discussion meant to facilitate growth and discovery. This workshop allows for an intimate setting where members can talk openly about the challenges faced by LGBTQ+ people and their families and friends and share tools they've used to overcome these challenges.", room: "Bohr", map: "Adobe-3")
            return[workshop1,workshop2,workshop3,workshop4,workshop5,workshop6,workshop7,workshop8,workshop9,workshop10,workshop11]
        }
        var youthWorkshop2: [Workshop] {
            let workshop1 = Workshop(name: "Workshop 3", title: "BEYOND", time: sessionTwoTime, description: "A night of music in which all members of the community are welcome to come sing, play/bring instruments, laugh, and jam together.", room: "Music Room", map: "Adobe-3")
            let workshop2 = Workshop(name: "Workshop 3", title: "Elevate", time: sessionTwoTime, description: "A speaking series in which Encircle invites successful, thriving, inspirational LGBTQ+ individuals with diverse backgrounds and life journeys from the community to come and share their story.", room: "Pele/Ruth", map: "Adobe-2")
             let workshop3 = Workshop(name: "Workshop 3", title: "Love Louder Art Series", time: sessionTwoTime, description: "Add color to your life through creative and artistic expression. This workshop hosted by masters of their craft provides new skills and coping strategies. No artistic experience necessary!", room: "Alphabravo", map: "Adobe-1")
            let workshop4 = Workshop(name: "Workshop 3", title: "Blue Sky", time: sessionTwoTime, description: "Clear away cloudy days by putting pencil to paper. This workshop provides a safe space to find your voice through writing. ", room: "Miyamoto", map: "Adobe-4")
            let workshop5 = Workshop(name: "Workshop 3", title: "Friendship Circles", time: sessionTwoTime, description: "FIND SUPPORT, VALIDATION, AND LEARN FROM EACH OTHER’S EXPERIENCES", room: "Hoff/Cailiau/Torvalds/Geschke", map: "Adobe-4")
            let workshop6 = Workshop(name: "Workshop 3", title: "Tools to Thrive: Become Your Own Therapist", time: sessionTwoTime, description: "This program will draw upon research regarding cognitive behavioral therapy and provide techniques which participants can employ to thrive despite queer challenges.", room: "Tesla", map: "Adobe-3")
            let workshop7 = Workshop(name: "Workshop 3", title: "Rainbow Mutual", time: sessionTwoTime, description: "Come make Rainbow Pins with your friends!", room: "Gould/Bell", map: "Adobe-3")
            let workshop8 = Workshop(name: "Workshop 3", title: "Gender Q&A Panel", time: sessionTwoTime, description: "A panel of transgender, gender non-conforming, and a partner of someone who is will be opening up about their identities, their experiences, and their lives. Come listen to them tell their stories, and ask questions. Learn about gender identity, and what that can look like in a variety of ways.", room: "Newton", map: "Adobe-3")
            let workshop9 = Workshop(name: "Workshop 3", title: "Tools to Thrive", time: sessionTwoTime, description: "Join Dolls of Hope in a discussion meant to facilitate growth and discovery. This workshop allows for an intimate setting where members can talk openly about the challenges faced by LGBTQ+ people and their families and friends and share tools they've used to overcome these challenges.", room: "Bohr", map: "Adobe-3")
            return[workshop1,workshop2,workshop3,workshop4,workshop5,workshop6,workshop7,workshop8,workshop9]
        }
        var youthWorkshop3: [Workshop] {
            let workshop1 = Workshop(name: "Workshop 4", title: "Tools to Thrive", time: sessionThreeTime, description: "A discussion-based workshop meant to facilitate growth and discovery in an intimate setting where community members can talk openly about the challenges faced by LGBTQ+ people and their families and friends and share tools they’ve used to overcome these challenges.", room: "Pollock", map: "Adobe-1")
            let workshop2 = Workshop(name: "Workshop 4", title: "BEYOND", time: sessionThreeTime, description: "A night of music in which all members of the community are welcome to come sing, play/bring instruments, laugh, and jam together.", room: "Music Room", map: "Adobe-3")
            let workshop3 = Workshop(name: "Workshop 4", title: "Elevate", time: sessionThreeTime, description: "A speaking series in which Encircle invites successful, thriving, inspirational LGBTQ+ individuals with diverse backgrounds and life journeys from the community to come and share their story.", room: "Pele/Ruth", map: "Adobe-2")
            let workshop4 = Workshop(name: "Workshop 4", title: "Love Louder Art Series", time: sessionThreeTime, description: "Add color to your life through creative and artistic expression. This workshop hosted by masters of their craft provides new skills and coping strategies. No artistic experience necessary!", room: "Alphabravo", map: "Adobe-1")
            let workshop5 = Workshop(name: "Workshop 4", title: "Blue Sky", time: sessionThreeTime, description: "Clear away cloudy days by putting pencil to paper. This workshop provides a safe space to find your voice through writing.", room: "Miyamoto", map: "Adobe-4")
            let workshop6 = Workshop(name: "Workshop 4", title: "Friendship Circles", time: sessionThreeTime, description: "FIND SUPPORT, VALIDATION, AND LEARN FROM EACH OTHER’S EXPERIENCES", room: "Hoff/Cailiau/Torvalds/Geschke", map: "Adobe-4")
            let workshop7 = Workshop(name: "Workshop 4", title: "Tools to Thrive: Featuring Fidelity", time: sessionThreeTime, description: "Fidelity Investments will lead a discussion designed to help you identify your personal strengths and personal brand as you prepare for your next interview for a job or at school. We hope you can join this exciting discussion, the breakout session will conclude with a fun game and prizes that will help you increase your financial knowledge and capabilities!", room: "Tesla", map: "Adobe-3")
            let workshop8 = Workshop(name: "Workshop 4", title: "Rainbow Mutual", time: sessionThreeTime, description: "Come make Rainbow Pins with your friends!", room: "Gould/Bell", map: "Adobe-3")
            let workshop9 = Workshop(name: "Workshop 4", title: "Gender Q&A Panel", time: sessionThreeTime, description: "A panel of transgender, gender non-conforming, and a partner of someone who is will be opening up about their identities, their experiences, and their lives. Come listen to them tell their stories, and ask questions. Learn about gender identity, and what that can look like in a variety of ways.", room: "Newton", map: "Adobe-3")
            let workshop10 = Workshop(name: "Workshop 4", title: "Tools to Thrive", time: sessionThreeTime, description: "Join Dolls of Hope in a discussion meant to facilitate growth and discovery. This workshop allows for an intimate setting where members can talk openly about the challenges faced by LGBTQ+ people and their families and friends and share tools they've used to overcome these challenges.", room: "Bohr", map: "Adobe-3")
            return[workshop1,workshop2,workshop3,workshop4,workshop5,workshop6,workshop7,workshop8,workshop9,workshop10]
        }
        return[youthWorkshop1, youthWorkshop2, youthWorkshop3]
    }
    

    
    //YOUNG ADULT WORKSHOPS
     var youngAdultWokshops: [[Workshop]]{
        var youngAdultWorkshop1: [Workshop] {
            let workshop1 = Workshop(name: "Workshop 2", title: "BEYOND", time: sessionOneTime, description: "A night of music in which all members of the community are welcome to come sing, play/bring instruments, laugh, and jam together.", room: "Music Room", map: "Adobe-3")
            let workshop2 = Workshop(name: "Workshop 2", title: "Tools to Thrive: Featuring Trevor Project", time: sessionOneTime, description: "Suicide Prevention and Crisis Response, Freaturing Trevor Project", room: "Tesla", map: "Adobe-3")
            let workshop3 = Workshop(name: "Workshop 2", title: "Elevate", time: sessionOneTime, description: "A speaking series in which Encircle invites successful, thriving, inspirational LGBTQ+ individuals with diverse backgrounds and life journeys from the community to come and share their story.", room: "Pele/Ruth", map: "Adobe-2")
            let workshop4 = Workshop(name: "Workshop 2", title: "WayOUT Panel", time: sessionOneTime, description: "WayOUT was started by a group of friends in San Francisco to help change what it means to grow up as a sexual minority in America. Come chat with three of wayOUT's members about their own personal experiences from coming out to building their professional careers and everything in between.", room: "Pollock", map: "Adobe-1")
            let workshop5 = Workshop(name: "Workshop 2", title: "Trans Experiences: Understanding, navigating and normalizing", time: sessionOneTime, description: "This Workshop invites participants to hear stories and share their personal experiences with intersectional gender, race and class. Peppermint will share her journey and discuss how it influences who she is today.", room: "Spielberg/Lucas", map: "Adobe-1")
            let workshop6 = Workshop(name: "Workshop 2", title: "Love Louder Art Series", time: sessionOneTime, description: "Add color to your life through creative and artistic expression. This workshop hosted by masters of their craft provides new skills and coping strategies. No artistic experience necessary!", room: "Alphabravo", map: "Adobe-1")
            let workshop7 = Workshop(name: "Workshop 2", title: "Blue Sky", time: sessionOneTime, description: "Clear away cloudy days by putting pencil to paper. Facilitated by writing professionals, this workshop provides a safe space to find your voice through writing.", room: "Da Vinci", map: "Adobe-1")
            let workshop8 = Workshop(name: "Workshop 2", title: "Becoming", time: sessionOneTime, description: "An workshop to strengthen understanding and dialogue between gender variant persons and their family members, allies, and community.", room: "Michelangelo", map: "Adobe-1")
            let workhop9 = Workshop(name: "Workshop 2", title: "Serve", time: sessionOneTime, description: "A service based workshop designed to foster connection between youth, their families, and the community at large.", room: "Rodan", map: "Adobe-1")
           
            return[workshop1,workshop2,workshop3,workshop4,workshop5,workshop6,workshop7,workshop8,workhop9]
        }
        var youngAdultWorkshop2: [Workshop] {
            let workshop1 = Workshop(name: "Workshop 3", title: "BEYOND", time: sessionTwoTime, description: "A night of music in which all members of the community are welcome to come sing, play/bring instruments, laugh, and jam together.", room: "Music Room", map: "Adobe-3")
            let workshop2 = Workshop(name: "Workshop 3", title: "Elevate", time: sessionTwoTime, description: "A speaking series in which Encircle invites successful, thriving, inspirational LGBTQ+ individuals with diverse backgrounds and life journeys from the community to come and share their story.", room: "Pele/Ruth", map: "Adobe-2")
             let workshop3 = Workshop(name: "Workshop 3", title: "Love Louder Art Series", time: sessionTwoTime, description: "Add color to your life through creative and artistic expression. This workshop hosted by masters of their craft provides new skills and coping strategies. No artistic experience necessary!", room: "Alphabravo", map: "Adobe-1")
             let workshop4 = Workshop(name: "Workshop 3", title: "Blue Sky", time: sessionTwoTime, description: "Clear away cloudy days by putting pencil to paper. Facilitated by writing professionals, this workshop provides a safe space to find your voice through writing.", room: "Da Vinci", map: "Adobe-1")
            let workshop5 = Workshop(name: "Workshop 3", title: "The Future Project", time: sessionTwoTime, description: "A new generation is on the rise and queer youth are on the front lines of this creative revolution. James Lecesne (writer/performer/founder of The Trevor Project) and Ryan Amador (singer/songwriter) will guide a group of young people in true storytelling & songwriting exercises. Express Yourself with words and song!", room: "Lucas", map: "Adobe-1")
            let workshop6 = Workshop(name: "Workshop 3", title: "Becoming", time: sessionTwoTime, description: "An workshop to strengthen understanding and dialogue between gender variant persons and their family members, allies, and community.", room: "Michelangelo", map: "Adobe-1")
            let workhop7 = Workshop(name: "Workshop 3", title: "Serve", time: sessionTwoTime, description: "A service based workshop designed to foster connection between youth, their families, and the community at large.", room: "Rodan", map: "Adobe-1")
            return[workshop1,workshop2,workshop3,workshop4,workshop5,workshop6,workhop7]
        }
        var youngAdultWorkshop3: [Workshop] {
            let workshop1 = Workshop(name: "Workshop 4", title: "Tools to Thrive", time: sessionThreeTime, description: "A discussion-based workshop meant to facilitate growth and discovery in an intimate setting where community members can talk openly about the challenges faced by LGBTQ+ people and their families and friends and share tools they’ve used to overcome these challenges.", room: "Pollock", map: "Adobe-1")
            let workshop2 = Workshop(name: "Workshop 4", title: "BEYOND", time: sessionThreeTime, description: "A night of music in which all members of the community are welcome to come sing, play/bring instruments, laugh, and jam together.", room: "Music Room", map: "Adobe-3")
            let workshop3 = Workshop(name: "Workshop 4", title: "Elevate", time: sessionThreeTime, description: "A speaking series in which Encircle invites successful, thriving, inspirational LGBTQ+ individuals with diverse backgrounds and life journeys from the community to come and share their story.", room: "Pele/Ruth", map: "Adobe-2")
            let workshop4 = Workshop(name: "Workshop 4", title: "Love Louder Art Series", time: sessionThreeTime, description: "Add color to your life through creative and artistic expression. This workshop hosted by masters of their craft provides new skills and coping strategies. No artistic experience necessary!", room: "Alphabravo", map: "Adobe-1")
             let workshop5 = Workshop(name: "Workshop 4", title: "Blue Sky", time: sessionThreeTime, description: "Clear away cloudy days by putting pencil to paper. Facilitated by writing professionals, this workshop provides a safe space to find your voice through writing.", room: "Da Vinci", map: "Adobe-1")
            let workshop6 = Workshop(name: "Workshop 4", title: "The Future Project", time: sessionThreeTime, description: "A new generation is on the rise and queer youth are on the front lines of this creative revolution. James Lecesne (writer/performer/founder of The Trevor Project) and Ryan Amador (singer/songwriter) will guide a group of young people in true storytelling & songwriting exercises. Express Yourself with words and song!", room: "Lucas", map: "Adobe-1")
            let workshop7 = Workshop(name: "Workshop 4", title: "Becoming", time: sessionThreeTime, description: "An workshop to strengthen understanding and dialogue between gender variant persons and their family members, allies, and community.", room: "Michelangelo", map: "Adobe-1")
            let workhop8 = Workshop(name: "Workshop 4", title: "Serve", time: sessionThreeTime, description: "A service based workshop designed to foster connection between youth, their families, and the community at large.", room: "Rodan", map: "Adobe-1")
            return[workshop1,workshop2,workshop3,workshop4,workshop5,workshop6,workshop7,workhop8]
        }
        return[youngAdultWorkshop1, youngAdultWorkshop2, youngAdultWorkshop3]
    }
    
    //ADULT WORKSHOPS
    var  adultWorkhops: [[Workshop]]{
        var adultWorkshop1: [Workshop] {
            let workshop1 = Workshop(name: "Workshop 1", title: "Cultural Identity's Impact on Health", time: sessionOneTime, description: "cultural identity and how it influences the 5 main aspects of personal health, which are emotional, occupational, intellectual, social community environment, physical fitness nutrition, spiritual values ethics.", room: "429", map: "Podium-4")
            let workshop2 = Workshop(name: "Workshop 1", title: "Bearing Your Journey (Without Murmuring)", time: sessionOneTime, description: "The journey of an LGBT Saint in the Church of Jesus Christ of Latter-day Saints can seem like an unending journey in the wilderness. Do we exclaim “It is a hard thing.” or “How is it possible?” and give up? Or do we rejoice in the journey knowing that with God we can bear all trials?", room: "430", map: "Podium-4")
            let workshop3 = Workshop(name: "Workshop 1", title: "Life After Coming Out", time: sessionOneTime, description: "With combined self-love and compassion we will navigate the different obstacles in life after coming out in a safe and open environment. We all have something unique to learn from each other by sharing our stories", room: "421", map: "Podium-4")
            let workshop4 = Workshop(name: "Workshop 1", title: "Legal Protections: Know Your Rights", time: sessionOneTime, description: "Asaf Orr is a Senior Staff Attorney on the Transgender Youth Project for the National Center for Lesbian Rights. He has worked to help people, specifically trans youth, know and understand what their rights are when it comes to legal issues.", room: "422", map: "Podium-4")
            let workshop5 = Workshop(name: "Workshop 1", title: "The Power of Storytelling", time: sessionOneTime, description: "As a parent of an LGBTQ+ child in most cases it can be hard for you to feel like you can help them unless you are LGBTQ+ yourself. Because you are not a part of the same demographic and can be hard for you to relate, share personal stories and even help them understand who they are. As a parent of an LGBTQ+ child it can also be difficult for you to understand how to help them because acceptance begins at the root of a queer child’s life and perspective on their future. Many of them have parents who do not accept them or who do not understand them. In this workshop we will discuss the power of storytelling and how it is important to help your child relate to their peers but also how it is important to share your stories to help educate yourselves, your child and other parents.", room: "418", map: "Podium-4")
            let workshop6 =  Workshop(name: "Workshop 1", title: "My Story: A panel moderated by Wendy VonSosen, President of Mama Dragons, featuring Emma Gee", time: sessionOneTime, description: "Hear more about Emma Gee's story and what it's like to be the first out athlete at BYU Provo.", room: "322", map: "Podium-3")
            let workshop7 = Workshop(name: "Workshop 1", title: "I am Transgender: A Conversation with Jen Richards", time: sessionOneTime, description: "Come have a conversation with Jen Richards, a successful activist, writer, actress and producer. Jen will talk openly and honestly about her journey as a transgender woman.", room: "333", map: "Podium-3")
            let workshop8 = Workshop(name: "Workshop 1", title: "Gender Identity", time: sessionOneTime, description: "A presentation regarding gender identity, transitioning, legal issues, and how we can help.", room: "234", map: "Podium-2")
            let workshop9 = Workshop(name: "Workshop 1", title: "What your LGBTQ+ friends and family want you to know about coming out", time: sessionOneTime, description: "Come have a discussion with Matt Easton, the BYU Validictorian who came out in his graduation speech", room: "240", map: "Podium-2")
            let workshop10 = Workshop(name: "Workshop 1", title: "Guardians of Safe Spaces", time: sessionOneTime, description: "We will focus on what safe spaces look like, feel like, and sound like. We will work through communication skills necessary to have difficult conversations. The workshop will focus on building whole-hearted relationships. The workshop will also include the voices of students describing what they want and need in the classroom and at home.", room: "231", map: "Podium-2")
            let workshop11 = Workshop(name: "Workshop 1", title: "Dealing with Coming Out", time: sessionOneTime, description: "Come here more of Ed Smart's story", room: "131", map: "Podium-1")
            let workshop12 = Workshop(name: "Workshop 1", title: "God will never leave you", time: sessionOneTime, description: "The story of how a gay man found an even deeper connection to God outside of religion and the comfort of his faith. Through personal stories of encouragement and his heartfelt testimony of God’s ravishing and relentless love, Marcelo Gomes will share how he found freedom from reparative therapy, negative self-image, and religious conditioning, to finally live a life of freedom and meaning as an LGBTQ Christian. His story will remind you that God won’t ever leave you; even when you think He may have! ", room: "433", map: "Podium-4")
            let workshop13 = Workshop(name: "Workshop 1", title: "Reconciling Faith with Lived Experence", time: sessionOneTime, description: "What do we do when our or a loved one's sexual orientation or gender identity feels incompatible with our ideas of faith or religious identities? In this section, we will confront these painful contradictions with compassionate respect and offer tools to process the painful emotions that are brought on by them.", room: "312", map: "Podium-3")
            return[workshop1,workshop2,workshop3,workshop4,workshop5,workshop6,workshop7,workshop8,workshop9,workshop10,workshop11,workshop12,workshop13]
        }
        var adultWorkshop2: [Workshop] {
            let workshop1 = Workshop(name: "Workshop 2", title: "Finding the Courage to Push Through Adversity", time: sessionTwoTime, description: "It's upon you to make your own choices, get up when you fall, and have the courage to overcome adversity. Mondo comes from Mesa, AZ. He is half Navajo Indian and half black, and spent his youth on the Navajo reservation. Mondo went on Native American Indian placement program with LDS Church. Upon graduating from high school with track scholarship to BYU, he served on LDS mission to Oklahoma City. He served as an EFY counselor for 4 years, went on to graduate from UVSC and then University of Utah in Electronic Journalism. He is currently the Head Volleyball coach at Skyline High, and the Youth Director at Club V Volleyball. He has been with his partner for 14 years, and they have been married for 1 year. They have 24 grandchildren!", room: "429", map: "Podium-4")
            let workshop2 = Workshop(name: "Workshop 2", title: "Bearing Your Journey (Without Murmuring)", time: sessionTwoTime, description: "The journey of an LGBT Saint in the Church of Jesus Christ of Latter-day Saints can seem like an unending journey in the wilderness. Do we exclaim “It is a hard thing.” or “How is it possible?” and give up? Or do we rejoice in the journey knowing that with God we can bear all trials?", room: "430", map: "Podium-4")
            let workshop3 = Workshop(name: "Workshop 2", title: "Life After Coming Out", time: sessionTwoTime, description: "With combined self-love and compassion we will navigate the different obstacles in life after coming out in a safe and open environment. We all have something unique to learn from each other by sharing our stories", room: "421", map: "Podium-4")
            let workshop4 = Workshop(name: "Workshop 2", title: "Legal Protections: Know Your Rights", time: sessionTwoTime, description: "Asaf Orr is a Senior Staff Attorney on the Transgender Youth Project for the National Center for Lesbian Rights. He has worked to help people, specifically trans youth, know and understand what their rights are when it comes to legal issues.", room: "422", map: "Podium-4")
            let workshop5 = Workshop(name: "Workshop 2", title: "Distress Management", time: sessionTwoTime, description: "I can't remember if there was ever a time I wasn't stressed. What do I do about this? How can I deal with stress? This workshop focuses on how to healthily handle distressing emotions and experiences.", room: "418", map: "Podium-4")
            let workshop6 = Workshop(name: "Workshop 2", title: "A Friendship Circle led by Charlie Bird", time: sessionTwoTime, description: "FIND SUPPORT, VALIDATION, AND LEARN FROM EACH OTHER’S EXPERIENCES ", room: "234", map: "Podium-2")
            let workshop7 = Workshop(name: "Workshop 2", title: "QPR Training", time: sessionTwoTime, description: "The QPR mission is to reduce suicidal behaviors and save lives by providing innovative, practical and proven suicide prevention training. The signs of crisis are all around us. We believe that quality education empowers all people, regardless of their background, to make a positive difference in the life of someone they know.", room: "240", map: "Podium-2")
               let workshop8 = Workshop(name: "Workshop 2", title: "Guardians of Safe Spaces", time: sessionTwoTime, description: "We will focus on what safe spaces look like, feel like, and sound like. We will work through communication skills necessary to have difficult conversations. The workshop will focus on building whole-hearted relationships. The workshop will also include the voices of students describing what they want and need in the classroom and at home.", room: "231", map: "Podium-2")
            let workshop9 = Workshop(name: "Workshop 2", title: "Gay Rights and the Mormon Church: Ask the Author", time: sessionTwoTime, description: "Greg Prince will engage the audience in an hour-long discussion of his recent book.", room: "131", map: "Podium-1")
            let workshop10 = Workshop(name: "Workshop 2", title: "God will never leave you", time: sessionTwoTime, description: "The story of how a gay man found an even deeper connection to God outside of religion and the comfort of his faith. Through personal stories of encouragement and his heartfelt testimony of God’s ravishing and relentless love, Marcelo Gomes will share how he found freedom from reparative therapy, negative self-image, and religious conditioning, to finally live a life of freedom and meaning as an LGBTQ Christian. His story will remind you that God won’t ever leave you; even when you think He may have! ", room: "433", map: "Podium-4")
            let workshop11 = Workshop(name: "Workshop 2", title: "Reconciling Faith with Lived Experence", time: sessionTwoTime, description: "What do we do when our or a loved one's sexual orientation or gender identity feels incompatible with our ideas of faith or religious identities? In this section, we will confront these painful contradictions with compassionate respect and offer tools to process the painful emotions that are brought on by them.", room: "312", map: "Podium-3")
            let workshop12 = Workshop(name: "Workshop 2", title: "A Friendship Circle led by Charlie Bird", time: sessionTwoTime, description: "FIND SUPPORT, VALIDATION, AND LEARN FROM EACH OTHER’S EXPERIENCES ", room: "234", map: "Podium-2")
            return[workshop1,workshop2,workshop3,workshop4,workshop5,workshop6,workshop7,workshop8,workshop9,workshop10,workshop11,workshop12]
        }
        var adultWorkshop3: [Workshop] {
            let workshop1 = Workshop(name: "Workshop 3", title: "Finding the Courage to Push Through Adversity", time: sessionThreeTime, description: "It's upon you to make your own choices, get up when you fall, and have the courage to overcome adversity. Mondo comes from Mesa, AZ. He is half Navajo Indian and half black, and spent his youth on the Navajo reservation. Mondo went on Native American Indian placement program with LDS Church. Upon graduating from high school with track scholarship to BYU, he served on LDS mission to Oklahoma City. He served as an EFY counselor for 4 years, went on to graduate from UVSC and then University of Utah in Electronic Journalism. He is currently the Head Volleyball coach at Skyline High, and the Youth Director at Club V Volleyball. He has been with his partner for 14 years, and they have been married for 1 year. They have 24 grandchildren!", room: "429", map: "Podium-4")
            let workshop2 = Workshop(name: "Workshop 3", title: "Bearing Your Journey (Without Murmuring)", time: sessionThreeTime, description: "The journey of an LGBT Saint in the Church of Jesus Christ of Latter-day Saints can seem like an unending journey in the wilderness. Do we exclaim “It is a hard thing.” or “How is it possible?” and give up? Or do we rejoice in the journey knowing that with God we can bear all trials?", room: "430", map: "Podium-4")
            let workshop3 = Workshop(name: "Workshop 3", title: "Two is better than one: Growing up with gay parents", time: sessionThreeTime, description: "Devin Preston, daughter of lesbian mothers, is ready to share all when it comes to being raised in a non-traditional household in a heteronormative world. She hopes her unique perspective will give insight into the world of parenting for LGBTQ+ couples and what their children experience.", room: "421", map: "Podium-4")
              let workshop4 = Workshop(name: "Workshop 3", title: "Legal Protections: Know Your Rights", time: sessionThreeTime, description: "Asaf Orr is a Senior Staff Attorney on the Transgender Youth Project for the National Center for Lesbian Rights. He has worked to help people, specifically trans youth, know and understand what their rights are when it comes to legal issues.", room: "422", map: "Podium-4")
            let workshop5 = Workshop(name: "Workshop 3", title: "Happiness & Mindfulness", time: sessionThreeTime, description: "What is happiness and how do I get more of it? I've heard this 'mindfulness' word thrown around as a panacea; why do hipsters keep talking about it? This workshop focuses on how our expectations and responses to emotion play a role in our happiness.", room: "418", map: "Podium-4")
            let workshop6 = Workshop(name: "Workshop 3", title: "WayOUT Panel", time: sessionThreeTime, description: "wayOUT was started by a group of friends in San Francisco to help change what it means to grow up as a sexual minority in America. Come chat with three of wayOUT's members about their own personal experiences from coming out to building their professional careers and everything in between.", room: "234", map:"Podium-4")
            let workshop7 = Workshop(name: "Workshop 3", title: "QPR Training", time: sessionThreeTime, description: "The QPR mission is to reduce suicidal behaviors and save lives by providing innovative, practical and proven suicide prevention training. The signs of crisis are all around us. We believe that quality education empowers all people, regardless of their background, to make a positive difference in the life of someone they know.", room: "240", map: "Podium-2")
            let workshop8 = Workshop(name: "Workshop 3", title: "Guardians of Safe Spaces", time: sessionThreeTime, description: "We will focus on what safe spaces look like, feel like, and sound like. We will work through communication skills necessary to have difficult conversations. The workshop will focus on building whole-hearted relationships. The workshop will also include the voices of students describing what they want and need in the classroom and at home.", room: "231", map: "Podium-2")
            let workshop9 = Workshop(name: "Workshop 3", title: "Building Healthy Futurees of LGBTQ+ Children & Youth: Learning from the Family Acceptance Project", time: sessionThreeTime, description: "A workshop for parents, caregivers and family members on affirming LGBTQ children and youth, and what we’ve learned from the first 20 years of research and family support work to decrease family rejection and prevent risk and increase family acceptance and support to promote health & well-being and strengthen families.", room: "131", map: "Podium-1")
            let workshop10 = Workshop(name: "Workshop 3", title: "God will never leave you", time: sessionThreeTime, description: "The story of how a gay man found an even deeper connection to God outside of religion and the comfort of his faith. Through personal stories of encouragement and his heartfelt testimony of God’s ravishing and relentless love, Marcelo Gomes will share how he found freedom from reparative therapy, negative self-image, and religious conditioning, to finally live a life of freedom and meaning as an LGBTQ Christian. His story will remind you that God won’t ever leave you; even when you think He may have! ", room: "433", map: "Podium-4")
            return[workshop1,workshop2,workshop3,workshop4,workshop5,workshop6,workshop7,workshop8,workshop9,workshop10]
        }
        return[adultWorkshop1, adultWorkshop2, adultWorkshop3]
    }
    
    
    
    //PARENT WORKSHOPS
    var parentWorkshops: [[Workshop]] {
        var parentWorkshop1: [Workshop] {
            let workshop1 = Workshop(name: "Workshop 1", title: "Legal Protections: Know Your Rights", time: sessionOneTime, description: "Asaf Orr is a Senior Staff Attorney on the Transgender Youth Project for the National Center for Lesbian Rights. He has worked to help people, specifically trans youth, know and understand what their rights are when it comes to legal issues.", room: "422", map: "Podium-4")
            let workshop2 = Workshop(name: "Workshop 1", title: "The Power of Storytelling", time: sessionOneTime, description: "As a parent of an LGBTQ+ child in most cases it can be hard for you to feel like you can help them unless you are LGBTQ+ yourself. Because you are not a part of the same demographic and can be hard for you to relate, share personal stories and even help them understand who they are. As a parent of an LGBTQ+ child it can also be difficult for you to understand how to help them because acceptance begins at the root of a queer child’s life and perspective on their future. Many of them have parents who do not accept them or who do not understand them. In this workshop we will discuss the power of storytelling and how it is important to help your child relate to their peers but also how it is important to share your stories to help educate yourselves, your child and other parents.", room: "418", map: "Podium-4")
            let workshop3 =  Workshop(name: "Workshop 1", title: "My Story: A panel moderated by Wendy VonSosen, President of Mama Dragons, featuring Emma Gee", time: sessionOneTime, description: "Hear more about Emma Gee's story and what it's like to be the first out athlete at BYU Provo.", room: "322", map: "Podium-3")
            let workshop4 = Workshop(name: "Workshop 1", title: "Reconciling Faith with Lived Experence", time: sessionOneTime, description: "What do we do when our or a loved one's sexual orientation or gender identity feels incompatible with our ideas of faith or religious identities? In this section, we will confront these painful contradictions with compassionate respect and offer tools to process the painful emotions that are brought on by them.", room: "312", map: "Podium-3")
             let workshop5 = Workshop(name: "Workshop 1", title: "I am Transgender: A Conversation with Jen Richards", time: sessionOneTime, description: "Come have a conversation with Jen Richards, a successful activist, writer, actress and producer. Jen will talk openly and honestly about her journey as a transgender woman.", room: "333", map: "Podium-3")
            let workshop6 = Workshop(name: "Workshop 1", title: "Gender Identity", time: sessionOneTime, description: "A presentation regarding gender identity, transitioning, legal issues, and how we can help.", room: "234", map: "Podium-2")
            let workshop7 = Workshop(name: "Workshop 1", title: "What your LGBTQ+ friends and family want you to know about coming out", time: sessionOneTime, description: "Come have a discussion with Matt Easton, the BYU Validictorian who came out in his graduation speech", room: "240", map: "Podium-2")
            let workshop8 = Workshop(name: "Workshop 1", title: "Guardians of Safe Spaces", time: sessionOneTime, description: "We will focus on what safe spaces look like, feel like, and sound like. We will work through communication skills necessary to have difficult conversations. The workshop will focus on building whole-hearted relationships. The workshop will also include the voices of students describing what they want and need in the classroom and at home.", room: "231", map: "Podium-2")
            let workshop9 = Workshop(name: "Workshop 1", title: "Dealing with Coming Out", time: sessionOneTime, description: "Come here more of Ed Smart's story", room: "131", map: "Podium-1")
            let workshop10 = Workshop(name: "Workshop 1", title: "Parent Support - A Friendship Circle", time: sessionOneTime, description: "Are you feeling the need to learn from other parents who are on the journey of raising their LGBTQ+ children? Meet with us in this space of learning and growing together through the expression of our shared experiences. This session will be a facilitated support group for parents and allies.", room: "410", map: "Podium-4")
            let workshop11 = Workshop(name: "Workshop 1", title: "Why you should talk to you teens about sexual health", time: sessionOneTime, description: "Coming out can be a big step for members of the LGBTQ+ community.  Come learn how to create a safe space for your LGBTQ+ friends and family and help them before, during, and after coming out.", room: "412", map: "Podium-4")
            let workshop12 = Workshop(name: "Workshop 1", title: "Parent Support - A Friendship Circle", time: sessionOneTime, description: "Are you feeling the need to learn from other parents who are on the journey of raising their LGBTQ+ children? Meet with us in this space of learning and growing together through the expression of our shared experiences. This session will be a facilitated support group for parents and allies.", room: "310", map: "Podium-3")
            let workshop13 = Workshop(name: "Workshop 1", title: "Creating a safe home environment for LGTBQ+ teens", time: sessionOneTime, description: "Providing the principles and tools for parents and teens to support common goals, including the principles of being present, coming from love versus fear, holding space, getting communication, non-attachment, and emotional intelligence.", room: "241", map: "Podium-2")
            let workshop14 = Workshop(name: "Workshop 1", title: "Parent Support - A Friendship Circle", time: sessionOneTime, description: "Are you feeling the need to learn from other parents who are on the journey of raising their LGBTQ+ children? Meet with us in this space of learning and growing together through the expression of our shared experiences. This session will be a facilitated support group for parents and allies.", room: "230", map: "Podium-2")
            let workshop15 = Workshop(name: "Workshop 1", title: "I see you.", time: sessionOneTime, description: "Autonomy is one of the most basic human needs and holds the key to our authenticity. Join with Cathy to explore the path to letting go of who you are supposed to be in favor of being who you are. This is a call to courage to give yourself the permission to show up and be seen for the important people in your lives. 'To thine own self be true.' --Shakespeare", room: "220", map: "Podium-2")
            let workshop16 = Workshop(name: "Workshop 1", title: "Connect: An Encircle Program Facilitated by Ken Hansen", time: sessionOneTime, description: "For parents and loved ones of LGBT individuals, a place where parents come to feel connected and supported by other parents, and leave feeling hope for their LGBT child's future, and theirs.", room: "210", map: "Podium-2")
            let workshop17 = Workshop(name: "Workshop 1", title: "Peculiar Panel: Creating an Unconditional Family", time: sessionOneTime, description: "Join our friends from Peculiar for a panel with Greg Prince, Bryce Cook, Mayor Kelleen Potter, and Michael Ferguson. Moderated by Paul Tew", room: "223", map: "Podium-2")
            
            return[workshop1,workshop2,workshop3,workshop4,workshop5,workshop6,workshop7,workshop8,workshop9,workshop10,workshop11,workshop12,workshop13,workshop14,workshop15,workshop16,workshop17]
        }
        var parentWorkshop2: [Workshop] {
            let workshop1 = Workshop(name: "Workshop 2", title: "Legal Protections: Know Your Rights", time: sessionTwoTime, description: "Asaf Orr is a Senior Staff Attorney on the Transgender Youth Project for the National Center for Lesbian Rights. He has worked to help people, specifically trans youth, know and understand what their rights are when it comes to legal issues.", room: "422", map: "Podium-4")
            let workshop2 = Workshop(name: "Workshop 2", title: "Distress Management", time: sessionTwoTime, description: "I can't remember if there was ever a time I wasn't stressed. What do I do about this? How can I deal with stress? This workshop focuses on how to healthily handle distressing emotions and experiences.", room: "418", map: "Podium-4")
            let workshop3 = Workshop(name: "Workshop 2", title: "Reconciling Faith with Lived Experence", time: sessionTwoTime, description: "What do we do when our or a loved one's sexual orientation or gender identity feels incompatible with our ideas of faith or religious identities? In this section, we will confront these painful contradictions with compassionate respect and offer tools to process the painful emotions that are brought on by them.", room: "312", map: "Podium-3")
            let workshop4 = Workshop(name: "Workshop 2", title: "A Friendship Circle led by Charlie Bird", time: sessionTwoTime, description: "FIND SUPPORT, VALIDATION, AND LEARN FROM EACH OTHER’S EXPERIENCES ", room: "234", map: "Podium-2")
            let workshop5 = Workshop(name: "Workshop 2", title: "QPR Training", time: sessionTwoTime, description: "The QPR mission is to reduce suicidal behaviors and save lives by providing innovative, practical and proven suicide prevention training. The signs of crisis are all around us. We believe that quality education empowers all people, regardless of their background, to make a positive difference in the life of someone they know.", room: "240", map: "Podium-2")
            let workshop6 = Workshop(name: "Workshop 2", title: "Guardians of Safe Spaces", time: sessionTwoTime, description: "We will focus on what safe spaces look like, feel like, and sound like. We will work through communication skills necessary to have difficult conversations. The workshop will focus on building whole-hearted relationships. The workshop will also include the voices of students describing what they want and need in the classroom and at home.", room: "231", map: "Podium-2")
            let workshop7 = Workshop(name: "Workshop 2", title: "Gay Rights and the Mormon Church: Ask the Author", time: sessionTwoTime, description: "Greg Prince will engage the audience in an hour-long discussion of his recent book.", room: "131", map: "Podium-1")
            let workshop8 = Workshop(name: "Workshop 2", title: "Parent Support - A Friendship Circle", time: sessionTwoTime, description: "Are you feeling the need to learn from other parents who are on the journey of raising their LGBTQ+ children? Meet with us in this space of learning and growing together through the expression of our shared experiences. This session will be a facilitated support group for parents and allies.", room: "410", map: "Podium-4")
            let workshop9 = Workshop(name: "Workshop 2", title: "Why you should talk to you teens about sexual health", time: sessionTwoTime, description: "Coming out can be a big step for members of the LGBTQ+ community.  Come learn how to create a safe space for your LGBTQ+ friends and family and help them before, during, and after coming out.", room: "412", map: "Podium-4")
            let workshop10 = Workshop(name: "Workshop 2", title: "Parent Support - A Friendship Circle", time: sessionTwoTime, description: "Are you feeling the need to learn from other parents who are on the journey of raising their LGBTQ+ children? Meet with us in this space of learning and growing together through the expression of our shared experiences. This session will be a facilitated support group for parents and allies.", room: "310", map: "Podium-3")
            let workshop11 = Workshop(name: "Workshop 2", title: "How to advocate for your LGBTQ+ child in the K-12 Setting", time: sessionTwoTime, description: "Q&A Session with School Administrators", room: "327", map: "Podium-3")
            let workshop12 = Workshop(name: "Workshop 2", title: "Creating a safe home environment for LGTBQ+ teens", time: sessionTwoTime, description: "Providing the principles and tools for parents and teens to support common goals, including the principles of being present, coming from love versus fear, holding space, getting communication, non-attachment, and emotional intelligence.", room: "241", map: "Podium-2")
            let workshop13 = Workshop(name: "Workshop 2", title: "Parent Support - A Friendship Circle", time: sessionTwoTime, description: "Are you feeling the need to learn from other parents who are on the journey of raising their LGBTQ+ children? Meet with us in this space of learning and growing together through the expression of our shared experiences. This session will be a facilitated support group for parents and allies.", room: "230", map: "Podium-2")
            let workshop14 = Workshop(name: "Workshop 2", title: "I see you.", time: sessionTwoTime, description: "Autonomy is one of the most basic human needs and holds the key to our authenticity. Join with Cathy to explore the path to letting go of who you are supposed to be in favor of being who you are. This is a call to courage to give yourself the permission to show up and be seen for the important people in your lives. 'To thine own self be true.' --Shakespeare", room: "220", map: "Podium-2")
            let workshop15 = Workshop(name: "Workshop 2", title: "Connect: An Encircle Program Facilitated by Ken Hansen", time: sessionTwoTime, description: "For parents and loved ones of LGBT individuals, a place where parents come to feel connected and supported by other parents, and leave feeling hope for their LGBT child's future, and theirs.", room: "210", map: "Podium-2")
            let workshop16 = Workshop(name: "Workshop 2", title: "Small Ideas, Big Results: How One Utah Community Demonstrated Inclusion of and Support for Its LGBTQ Community", time: sessionTwoTime, description: "Heber City Mayor Kelleen Potter and former Heber Valley resident Allison Phillips Belnap discuss their personal experiences leading them to the realization that their community was not safe or welcoming for LGBTQ folks and how their seemingly small efforts to demonstrate acceptance and inclusivity resonated in the Wasatch Back, throughout the state of Utah, and across the nation.", room: "223", map: "Podium-2")
            return[workshop1,workshop2,workshop3,workshop4,workshop5,workshop6,workshop7,workshop8,workshop9,workshop10,workshop11,workshop12,workshop13,workshop14,workshop15,workshop16]
        }
        var parentWorkshop3: [Workshop] {
            let workshop1 = Workshop(name: "Workshop 3", title: "Legal Protections: Know Your Rights", time: sessionThreeTime, description: "Asaf Orr is a Senior Staff Attorney on the Transgender Youth Project for the National Center for Lesbian Rights. He has worked to help people, specifically trans youth, know and understand what their rights are when it comes to legal issues.", room: "422", map: "Podium-4")
            let workshop2 = Workshop(name: "Workshop 3", title: "Happiness & Mindfulness", time: sessionThreeTime, description: "What is happiness and how do I get more of it? I've heard this 'mindfulness' word thrown around as a panacea; why do hipsters keep talking about it? This workshop focuses on how our expectations and responses to emotion play a role in our happiness.", room: "418", map: "Podium-4")
             let workshop3 = Workshop(name: "Workshop 3", title: "WayOUT Panel", time: sessionThreeTime, description: "wayOUT was started by a group of friends in San Francisco to help change what it means to grow up as a sexual minority in America. Come chat with three of wayOUT's members about their own personal experiences from coming out to building their professional careers and everything in between.", room: "234", map:"Podium-4")
            let workshop4 = Workshop(name: "Workshop 3", title: "QPR Training", time: sessionThreeTime, description: "The QPR mission is to reduce suicidal behaviors and save lives by providing innovative, practical and proven suicide prevention training. The signs of crisis are all around us. We believe that quality education empowers all people, regardless of their background, to make a positive difference in the life of someone they know.", room: "240", map: "Podium-2")
            let workshop5 = Workshop(name: "Workshop 3", title: "Guardians of Safe Spaces", time: sessionThreeTime, description: "We will focus on what safe spaces look like, feel like, and sound like. We will work through communication skills necessary to have difficult conversations. The workshop will focus on building whole-hearted relationships. The workshop will also include the voices of students describing what they want and need in the classroom and at home.", room: "231", map: "Podium-2")
            let workshop6 = Workshop(name: "Workshop 3", title: "Building Healthy Futurees of LGBTQ+ Children & Youth: Learning from the Family Acceptance Project", time: sessionThreeTime, description: "A workshop for parents, caregivers and family members on affirming LGBTQ children and youth, and what we’ve learned from the first 20 years of research and family support work to decrease family rejection and prevent risk and increase family acceptance and support to promote health & well-being and strengthen families.", room: "131", map: "Podium-1")
            let workshop7 = Workshop(name: "Workshop 3", title: "Parent Support - A Friendship Circle", time: sessionThreeTime, description: "Are you feeling the need to learn from other parents who are on the journey of raising their LGBTQ+ children? Meet with us in this space of learning and growing together through the expression of our shared experiences. This session will be a facilitated support group for parents and allies.", room: "410", map: "Podium-4")
            let workshop8 = Workshop(name: "Workshop 3", title: "Why you should talk to you teens about sexual health", time: sessionThreeTime, description: "Coming out can be a big step for members of the LGBTQ+ community.  Come learn how to create a safe space for your LGBTQ+ friends and family and help them before, during, and after coming out.", room: "412", map: "Podium-4")
            let workshop9 = Workshop(name: "Workshop 3", title: "Parent Support - A Friendship Circle", time: sessionThreeTime, description: "Are you feeling the need to learn from other parents who are on the journey of raising their LGBTQ+ children? Meet with us in this space of learning and growing together through the expression of our shared experiences. This session will be a facilitated support group for parents and allies.", room: "310", map: "Podium-3")
            let workshop10 = Workshop(name: "Workshop 3", title: "How to advocate for your LGBTQ+ child in the K-12 Setting", time: sessionThreeTime, description: "Q&A Session with School Administrators", room: "327", map: "Podium-3")
            let workshop11 = Workshop(name: "Workshop 3", title: "Creating a safe home environment for LGTBQ+ teens", time: sessionThreeTime, description: "Providing the principles and tools for parents and teens to support common goals, including the principles of being present, coming from love versus fear, holding space, getting communication, non-attachment, and emotional intelligence.", room: "241", map: "Podium-2")
            let workshop12 = Workshop(name: "Workshop 3", title: "Parent Support - A Friendship Circle", time: sessionThreeTime, description: "Are you feeling the need to learn from other parents who are on the journey of raising their LGBTQ+ children? Meet with us in this space of learning and growing together through the expression of our shared experiences. This session will be a facilitated support group for parents and allies.", room: "230", map: "Podium-2")
            let workshop13 = Workshop(name: "Workshop 3", title: "I see you.", time: sessionThreeTime, description: "Autonomy is one of the most basic human needs and holds the key to our authenticity. Join with Cathy to explore the path to letting go of who you are supposed to be in favor of being who you are. This is a call to courage to give yourself the permission to show up and be seen for the important people in your lives. 'To thine own self be true.' --Shakespeare", room: "220", map: "Podium-2")
            let workshop14 = Workshop(name: "Workshop 3", title: "Connect: An Encircle Program Facilitated by Ken Hansen", time: sessionThreeTime, description: "For parents and loved ones of LGBT individuals, a place where parents come to feel connected and supported by other parents, and leave feeling hope for their LGBT child's future, and theirs.", room: "210", map: "Podium-2")
            let workshop15 = Workshop(name: "Workshop 3", title: "Small Ideas, Big Results: How One Utah Community Demonstrated Inclusion of and Support for Its LGBTQ Community", time: sessionThreeTime, description: "Heber City Mayor Kelleen Potter and former Heber Valley resident Allison Phillips Belnap discuss their personal experiences leading them to the realization that their community was not safe or welcoming for LGBTQ folks and how their seemingly small efforts to demonstrate acceptance and inclusivity resonated in the Wasatch Back, throughout the state of Utah, and across the nation.", room: "223", map: "Podium-2")
            return[workshop1,workshop2,workshop3,workshop4,workshop5,workshop6,workshop7,workshop8,workshop9,workshop10,workshop11,workshop12,workshop13,workshop14,workshop15]
        }
        return[parentWorkshop1, parentWorkshop2, parentWorkshop3]
    }
    
    
    
    //EDUCATOR WORKSHOPS
    var educatorWorkshops: [[Workshop]] {
         var educatorWorkshop1: [Workshop] {
            let workshop1 = Workshop(name: "Workshop 1", title: "Legal Protections: Know Your Rights", time: sessionOneTime, description: "Asaf Orr is a Senior Staff Attorney on the Transgender Youth Project for the National Center for Lesbian Rights. He has worked to help people, specifically trans youth, know and understand what their rights are when it comes to legal issues.", room: "422", map: "Podium-4")
            let workshop2 = Workshop(name: "Workshop 1", title: "The Power of Storytelling", time: sessionOneTime, description: "As a parent of an LGBTQ+ child in most cases it can be hard for you to feel like you can help them unless you are LGBTQ+ yourself. Because you are not a part of the same demographic and can be hard for you to relate, share personal stories and even help them understand who they are. As a parent of an LGBTQ+ child it can also be difficult for you to understand how to help them because acceptance begins at the root of a queer child’s life and perspective on their future. Many of them have parents who do not accept them or who do not understand them. In this workshop we will discuss the power of storytelling and how it is important to help your child relate to their peers but also how it is important to share your stories to help educate yourselves, your child and other parents.", room: "418", map: "Podium-4")
            let workshop3 =  Workshop(name: "Workshop 1", title: "My Story: A panel moderated by Wendy VonSosen, President of Mama Dragons, featuring Emma Gee", time: sessionOneTime, description: "Hear more about Emma Gee's story and what it's like to be the first out athlete at BYU Provo.", room: "322", map: "Podium-3")
            let workshop4 = Workshop(name: "Workshop 1", title: "Reconciling Faith with Lived Experence", time: sessionOneTime, description: "What do we do when our or a loved one's sexual orientation or gender identity feels incompatible with our ideas of faith or religious identities? In this section, we will confront these painful contradictions with compassionate respect and offer tools to process the painful emotions that are brought on by them.", room: "312", map: "Podium-3")
             let workshop5 = Workshop(name: "Workshop 1", title: "I am Transgender: A Conversation with Jen Richards", time: sessionOneTime, description: "Come have a conversation with Jen Richards, a successful activist, writer, actress and producer. Jen will talk openly and honestly about her journey as a transgender woman.", room: "333", map: "Podium-3")
            let workshop6 = Workshop(name: "Workshop 1", title: "Gender Identity", time: sessionOneTime, description: "A presentation regarding gender identity, transitioning, legal issues, and how we can help.", room: "234", map: "Podium-2")
            let workshop7 = Workshop(name: "Workshop 1", title: "What your LGBTQ+ friends and family want you to know about coming out", time: sessionOneTime, description: "Come have a discussion with Matt Easton, the BYU Validictorian who came out in his graduation speech", room: "240", map: "Podium-2")
            let workshop8 = Workshop(name: "Workshop 1", title: "Guardians of Safe Spaces", time: sessionOneTime, description: "We will focus on what safe spaces look like, feel like, and sound like. We will work through communication skills necessary to have difficult conversations. The workshop will focus on building whole-hearted relationships. The workshop will also include the voices of students describing what they want and need in the classroom and at home.", room: "231", map: "Podium-2")
            let workshop9 = Workshop(name: "Workshop 1", title: "Dealing with Coming Out", time: sessionOneTime, description: "Come here more of Ed Smart's story", room: "131", map: "Podium-1")
            let workshop10 = Workshop(name: "Workshop 1", title: "Identity and Ability", time: sessionOneTime, description: "Join a group discussion on the topics of disability and LGBT+ identity. We will explore how these interact on individual and community levels with a focus on personal experiences.", room: "342", map: "Podium-3")
            let workshop11 = Workshop(name: "Workshop 1", title: "What Youth-Serving Professionals and Parents Need to Know About the LGBTQ+ Community", time: sessionOneTime, description: "In this session, participants will: (1.) better understand the terminology associated with the LGBTQ community, as well as the differences between sexual orientation and gender identity; (2.) identify the challenges – as well as mental and health disparities – impacting LGBTQ youth; and (3.) learn about effective interventions to create supportive environments and safer schools for LGBTQ students.", room: "341", map: "Podium-3")
            let workshop12 = Workshop(name: "Workshop 1", title: "Educator Support - A Friendship Circle", time: sessionOneTime, description: "FIND SUPPORT, VALIDATION, AND LEARN FROM EACH OTHER’S EXPERIENCES", room: "322", map: "Podium-3")
            let workshop13 = Workshop(name: "Workshop 1", title: "Best Practices for a safe and inclusive school", time: sessionOneTime, description: "A Panel with the Park City Counseling Department moderated by Carol Anderson", room: "321", map: "Podium-3")
            let workshop14 = Workshop(name: "Workshop 1", title: "Making Queer identities visible in K12", time: sessionOneTime, description: "Supporting LGBTQ+ students through inclusive practices", room: "327", map: "Podium-3")
            let workshop15 = Workshop(name: "Workshop 1", title: "GLSEN", time: sessionOneTime, description: "A panel featuring GLSEN. We know educators play a key roles in creating affirming learing environments for LGBTQ+ youth. In addition to activating supportive educators, we believe in centering and uplifting student led movements which have powered initiatives like Day of Silence, Ally Week, and more.", room: "326", map: "Podium-3")
            return[workshop1,workshop2,workshop3,workshop4,workshop5,workshop6,workshop7,workshop8,workshop9,workshop10,workshop11,workshop12,workshop13,workshop14,workshop15]
        }
         var educatorWorkshop2: [Workshop] {
            let workshop1 = Workshop(name: "Workshop 2", title: "Legal Protections: Know Your Rights", time: sessionTwoTime, description: "Asaf Orr is a Senior Staff Attorney on the Transgender Youth Project for the National Center for Lesbian Rights. He has worked to help people, specifically trans youth, know and understand what their rights are when it comes to legal issues.", room: "422", map: "Podium-4")
            let workshop2 = Workshop(name: "Workshop 2", title: "Distress Management", time: sessionTwoTime, description: "I can't remember if there was ever a time I wasn't stressed. What do I do about this? How can I deal with stress? This workshop focuses on how to healthily handle distressing emotions and experiences.", room: "418", map: "Podium-4")
            let workshop3 = Workshop(name: "Workshop 2", title: "Reconciling Faith with Lived Experence", time: sessionTwoTime, description: "What do we do when our or a loved one's sexual orientation or gender identity feels incompatible with our ideas of faith or religious identities? In this section, we will confront these painful contradictions with compassionate respect and offer tools to process the painful emotions that are brought on by them.", room: "312", map: "Podium-3")
            let workshop4 = Workshop(name: "Workshop 2", title: "A Friendship Circle led by Charlie Bird", time: sessionTwoTime, description: "FIND SUPPORT, VALIDATION, AND LEARN FROM EACH OTHER’S EXPERIENCES ", room: "234", map: "Podium-2")
            let workshop5 = Workshop(name: "Workshop 2", title: "QPR Training", time: sessionTwoTime, description: "The QPR mission is to reduce suicidal behaviors and save lives by providing innovative, practical and proven suicide prevention training. The signs of crisis are all around us. We believe that quality education empowers all people, regardless of their background, to make a positive difference in the life of someone they know.", room: "240", map: "Podium-2")
            let workshop6 = Workshop(name: "Workshop 2", title: "Guardians of Safe Spaces", time: sessionTwoTime, description: "We will focus on what safe spaces look like, feel like, and sound like. We will work through communication skills necessary to have difficult conversations. The workshop will focus on building whole-hearted relationships. The workshop will also include the voices of students describing what they want and need in the classroom and at home.", room: "231", map: "Podium-2")
            let workshop7 = Workshop(name: "Workshop 2", title: "Gay Rights and the Mormon Church: Ask the Author", time: sessionTwoTime, description: "Greg Prince will engage the audience in an hour-long discussion of his recent book.", room: "131", map: "Podium-1")
            let workshop8 = Workshop(name: "Workshop 2", title: "Identity and Ability", time: sessionTwoTime, description: "Join a group discussion on the topics of disability and LGBT+ identity. We will explore how these interact on individual and community levels with a focus on personal experiences.", room: "342", map: "Podium-3")
            let workshop9 = Workshop(name: "Workshop 2", title: "Understanding & Supporting the Mental Health Needs of LGBTQ+ Students", time: sessionTwoTime, description: "Millions of LGBTQ+ students are at risk for suicide and other poor mental health outcomes. There are numerous protective factors that may promote mental wellness for our LGBTQ+ students. This session will explore the existing research and discuss strategies that schools and educators can use to protect and support their LGBTQ+ students.", room: "332", map: "Podium-3")
            let workshop10 = Workshop(name: "Workshop 2", title: "Educator Support - A Friendship Circle", time: sessionTwoTime, description: "FIND SUPPORT, VALIDATION, AND LEARN FROM EACH OTHER’S EXPERIENCES", room: "322", map: "Podium-3")
            let workshop11 = Workshop(name: "Workshop 2", title: "Best Practices for a safe and inclusive school", time: sessionTwoTime, description: "A Panel with the Park City Counseling Department moderated by Carol Anderson", room: "321", map: "Podium-3")
            let workshop12 = Workshop(name: "Workshop 2", title: "GLSEN", time: sessionTwoTime, description: "A panel featuring GLSEN. We know educators play a key roles in creating affirming learing environments for LGBTQ+ youth. In addition to activating supportive educators, we believe in centering and uplifting student led movements which have powered initiatives like Day of Silence, Ally Week, and more.", room: "326", map: "Podium-3")
            return[workshop1,workshop2,workshop3,workshop4,workshop5,workshop6,workshop7,workshop8,workshop9,workshop10,workshop11,workshop12]
        }
         var educatorWorkshop3: [Workshop] {
            let workshop1 = Workshop(name: "Workshop 3", title: "Legal Protections: Know Your Rights", time: sessionThreeTime, description: "Asaf Orr is a Senior Staff Attorney on the Transgender Youth Project for the National Center for Lesbian Rights. He has worked to help people, specifically trans youth, know and understand what their rights are when it comes to legal issues.", room: "422", map: "Podium-4")
            let workshop2 = Workshop(name: "Workshop 3", title: "Happiness & Mindfulness", time: sessionThreeTime, description: "What is happiness and how do I get more of it? I've heard this 'mindfulness' word thrown around as a panacea; why do hipsters keep talking about it? This workshop focuses on how our expectations and responses to emotion play a role in our happiness.", room: "418", map: "Podium-4")
             let workshop3 = Workshop(name: "Workshop 3", title: "WayOUT Panel", time: sessionThreeTime, description: "wayOUT was started by a group of friends in San Francisco to help change what it means to grow up as a sexual minority in America. Come chat with three of wayOUT's members about their own personal experiences from coming out to building their professional careers and everything in between.", room: "234", map:"Podium-4")
            let workshop4 = Workshop(name: "Workshop 3", title: "QPR Training", time: sessionThreeTime, description: "The QPR mission is to reduce suicidal behaviors and save lives by providing innovative, practical and proven suicide prevention training. The signs of crisis are all around us. We believe that quality education empowers all people, regardless of their background, to make a positive difference in the life of someone they know.", room: "240", map: "Podium-2")
            let workshop5 = Workshop(name: "Workshop 3", title: "Guardians of Safe Spaces", time: sessionThreeTime, description: "We will focus on what safe spaces look like, feel like, and sound like. We will work through communication skills necessary to have difficult conversations. The workshop will focus on building whole-hearted relationships. The workshop will also include the voices of students describing what they want and need in the classroom and at home.", room: "231", map: "Podium-2")
            let workshop6 = Workshop(name: "Workshop 3", title: "Building Healthy Futurees of LGBTQ+ Children & Youth: Learning from the Family Acceptance Project", time: sessionThreeTime, description: "A workshop for parents, caregivers and family members on affirming LGBTQ children and youth, and what we’ve learned from the first 20 years of research and family support work to decrease family rejection and prevent risk and increase family acceptance and support to promote health & well-being and strengthen families.", room: "131", map: "Podium-1")
            let workshop7 = Workshop(name: "Workshop 3", title: "Identity and Ability", time: sessionThreeTime, description: "Join a group discussion on the topics of disability and LGBT+ identity. We will explore how these interact on individual and community levels with a focus on personal experiences.", room: "342", map: "Podium-3")
            let workshop8 = Workshop(name: "Workshop 3", title: "LGBTQ Inclusion in Utah Schools", time: sessionThreeTime, description: "This workshop will re-trace key steps toward LGBTQ inclusion in Utah schools beginning two decades ago with East High's first Gay-Straight Alliance. We will then discuss where things stand today, highlighting the people, programs, and best practices that empower our LGBTQ students and make Utah schools safer for all.", room: "312", map: "Podium-3")
            let workshop9 = Workshop(name: "Workshop 3", title: "Understanding & Supporting the Mental Health Needs of LGBTQ+ Students", time: sessionThreeTime, description: "Millions of LGBTQ+ students are at risk for suicide and other poor mental health outcomes. There are numerous protective factors that may promote mental wellness for our LGBTQ+ students. This session will explore the existing research and discuss strategies that schools and educators can use to protect and support their LGBTQ+ students.", room: "332", map: "Podium-3")
            let workshop10 = Workshop(name: "Workshop 3", title: "Educator Support - A Friendship Circle", time: sessionThreeTime, description: "FIND SUPPORT, VALIDATION, AND LEARN FROM EACH OTHER’S EXPERIENCES", room: "322", map: "Podium-3")
            let workshop11 = Workshop(name: "Workshop 3", title: "GLSEN", time: sessionThreeTime, description: "A panel featuring GLSEN. We know educators play a key roles in creating affirming learing environments for LGBTQ+ youth. In addition to activating supportive educators, we believe in centering and uplifting student led movements which have powered initiatives like Day of Silence, Ally Week, and more.", room: "326", map: "Podium-3")
            return[workshop1,workshop2,workshop3,workshop4,workshop5,workshop6,workshop7,workshop8,workshop9,workshop10,workshop11]
        }
        return[educatorWorkshop1, educatorWorkshop2, educatorWorkshop3]
    }
}
